# Generated by Django 4.2.7 on 2024-01-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
